services:
  queue:
    image: rabbitmq:alpine
    restart: on-failure:5

  db:
    image: postgres:alpine
    restart: on-failure:5
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  
  producer-ms:
    build: ./services/producer-ms
    restart: on-failure:5
    ports:
      - ${EXTERN_PORT}:8080
    volumes:
      - ./logs/producer-ms:/app/logs
    environment:
      - QUEUE_USERNAME=${QUEUE_USERNAME}
      - QUEUE_PASSWORD=${QUEUE_PASSWORD}
      - QUEUE_HOST=${QUEUE_HOST}
      - QUEUE_PORT=${QUEUE_PORT}

  consumer-ms:
    build: ./services/consumer-ms
    volumes:
      - ./logs/consumer-ms:/app/logs
    restart: on-failure:5
    environment:
      - QUEUE_USERNAME=${QUEUE_USERNAME}
      - QUEUE_PASSWORD=${QUEUE_PASSWORD}
      - QUEUE_HOST=${QUEUE_HOST}
      - QUEUE_PORT=${QUEUE_PORT}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PORT=${DB_PORT}
      - DATABASE=${DATABASE}